Change occurences of XDL to XBF in documentation
XtensibleBinaryFormat/XBF pull request #27
Opened 2023-06-22 01:54 UTC by dkrautha

Changes things in licenses and the README

2023-06-22 02:16 UTC, ahuston-0 approved these changes
All looks good to me. Not sure how this slipped by me with #25 and #26.

2023-06-22 02:19 UTC, ahuston-0 requested changes
Oof wait I just took another look at this. Definitely pull the latest version of `specification.md` and then make the changes. Looks like you changed XDL to XBF in places where we had removed outdated parts of the spec.

2023-06-23 02:27 UTC, TheMadMaker2 approved these changes

2023-06-23 02:31 UTC, TheMadMaker2 approved these changes

2023-06-23 03:10 UTC, ahuston-0 approved these changes
approved

2023-06-23 03:43 UTC, merged